package com.callee.calleeclient.client;

public enum ToM {
    MESSAGE,
    MESSAGERESPONSE,
    UPDATEREQUEST,
    UPDATERESPONSE,
    REGISTERUSER,
    REGISTERUSERRESPONSE,
    REGISTERCONFIRM,
    REGISTERCONFIRMRESPONSE,
    CONFIRMCONTACT,
    CONFIRMREAD
}